Projet/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
                  path('', include('Site.urls')),
                  path('Utilisateurs/', include('Utilisateurs.urls')),
                  path('administrer/', include('Admin.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

Site/urls.py
# Site/urls.py
from django.urls import path

from Site import views
from Site.views import Index

app_name = 'site'

urlpatterns = [
    path('', Index, name='index'),
    path('publication/<int:pk>/', views.publication_detail, name='publication_detail'),
]

Utilisateurs/urls.py
# Utilisateurs/urls.py
from django.urls import path
from .views import CustomLoginView, Index, Profile, CustomLogoutView, InscriptionView, CustomUserListView, \
    UserRegistrationView, message_list

app_name = 'utilisateurs'

urlpatterns = [
    path('', CustomLoginView.as_view(), name='connexion'),
    path('deconnexion/', CustomLogoutView.as_view(next_page='utilisateurs:connexion'), name='deconnexion'),
    path('inscription/', InscriptionView.as_view(), name='inscription'),
    path('index/', Index, name='Index'),
    path('index/', Index, name='Index'),
    path('profile/', Profile, name='Profile'),
    path('api/users/', CustomUserListView.as_view(), name='user-list'),
    path('api/inscription/', UserRegistrationView.as_view(), name='inscription_react'),
    path('api/messages/', message_list, name='message-list'),
]

Utilisateurs/models.py
# Utilisateurs/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models import Q
from django.forms import forms
from django.urls import reverse
from django.utils import timezone
from django.utils.timesince import timesince
from multiupload.fields import MultiFileField


class CustomUserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(username, password, **extra_fields)

    def get_user_messages(self, user, recipient):
        return Message.objects.filter(Q(sender=user, receiver=recipient) | Q(sender=recipient, receiver=user))


class CustomUser(AbstractBaseUser):
    ROLE_CHOICES = [
        ('user', 'User'),
        ('admin', 'Admin'),
    ]

    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='user')
    username = models.CharField(max_length=15, unique=True)
    nom = models.CharField(max_length=30)
    prenom = models.CharField(max_length=30)
    photo = models.ImageField(upload_to='profile_photos/', null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_online = models.BooleanField(default=False)
    last_logout = models.DateTimeField(default=timezone.now)
    unread_messages_count = models.IntegerField(default=0)

    @property
    def get_unread_messages(self):
        return Message.objects.filter(receiver=self, is_read=False).count()

    def time_since_last_logout(self):
        if self.last_logout:
            time_since_logout = timesince(self.last_logout)
            return f"En ligne il y a {time_since_logout}"
        else:
            return "Hors ligne (date de déconnexion non disponible)"

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['nom', 'prenom']

    def __str__(self):
        return f"{self.prenom} {self.nom}"


class Message(models.Model):
    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def mark_as_read(self):
        self.is_read = True
        self.save()

    def __str__(self):
        return f'{self.sender} to {self.receiver} ({self.timestamp})'


class BlogPost(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(get_user_model(), related_name='blog_likes', blank=True)
    shares = models.IntegerField(default=0)
    image = models.ImageField(upload_to='blog_images/', verbose_name="Image d'accueil", blank=True)
    views = models.IntegerField(default=0)

    def get_delete_url(self):
        return reverse('delete_post', args=[str(self.id)])

    def increment_views(self):
        self.views += 1
        self.save()

    def get_like_count(self):
        return self.likes.count()

    def __str__(self):
        return f"Image {self.pk}"

    def time_pub_date_since(self):
        if self.pub_date:
            time_since_pub_date = timesince(self.pub_date)
            return f"Publier il y a {time_since_pub_date}"
        else:
            return "Hors ligne (date de déconnexion non disponible)"

    def get_absolute_url(self):
        return reverse('blog:blog_detail', args=[str(self.id)])

    def __str__(self):
        return self.title

Utilisateurs/forms.py
# Utilisateurs/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import ClearableFileInput

from .models import CustomUser, BlogPost
from django import forms


class UserRegistrationForm(UserCreationForm):
    photo = forms.ImageField(required=False)
    username = forms.CharField(max_length=15, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Numéro de téléphone'}))
    role = forms.ChoiceField(choices=CustomUser.ROLE_CHOICES, required=False, widget=forms.Select(
        attrs={'class': 'form-control'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'nom', 'prenom', 'photo', 'password1', 'password2', 'role']

        def clean(self):
            cleaned_data = super().clean()

            password1 = cleaned_data.get("password1")
            password2 = cleaned_data.get("password2")

            if password1 and password2 and password1 != password2:
                self.add_error('password2', "Les deux mots de passe ne correspondent pas.")

            return cleaned_data

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['nom'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Nom'})
        self.fields['prenom'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Prénom'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Mot de passe'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Confirmez le mot de passe'})
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Numéro de téléphone'})


class UserAuthenticationForm(AuthenticationForm):
    username = forms.CharField(max_length=15, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Numéro de téléphone'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'password']


class MessageForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea)


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'content', 'image']


class ActivateUserForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput())


class DeactivateUserForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput())

Utilisateurs/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from rest_framework import generics, status, viewsets
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from .forms import UserRegistrationForm, UserAuthenticationForm
from .models import CustomUser, Message
from .serializers import CustomUserSerializer, UserRegistrationSerializer, MessageSerializer


class InscriptionView(View):
    template_name = 'inscription.html'

    def get(self, request, *args, **kwargs):
        form = UserRegistrationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = UserRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('utilisateurs:connexion')
        else:
            print(form.errors)
            return render(request, self.template_name, {'form': form})


class CustomLogoutView(LogoutView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            request.user.is_online = False
            request.user.last_logout = timezone.now()
            request.user.save()
        response = super().get(request, *args, **kwargs)
        return response


class CustomLoginView(LoginView):
    template_name = 'connexion.html'
    form_class = UserAuthenticationForm

    def get_success_url(self):
        user = self.request.user
        if user.is_authenticated:
            user.is_online = True
            user.save()
            if user.role == 'admin':
                return reverse_lazy('admin:admin_dashboard')
            else:
                return reverse_lazy('utilisateurs:Index')
        return super().get_success_url()

    def form_invalid(self, form):
        print("erreur. Errors:", form.errors)
        return super().form_invalid(form)


@login_required(login_url='utilisateurs:connexion')
def Index(request):
    return render(request, 'index2.html')


@login_required(login_url='utilisateurs:connexion')
@user_passes_test(lambda u: u.role == 'user')
def Profile(request):
    utilisateurs = CustomUser.objects.exclude(role="admin").exclude(id=request.user.id)
    context = {'all_users': utilisateurs}
    return render(request, 'profile.html', context)


class CustomUserListView(generics.ListAPIView):
    queryset = CustomUser.objects.all()
    serializer_class = CustomUserSerializer


class UserRegistrationView(generics.CreateAPIView):
    serializer_class = UserRegistrationSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)


@api_view(['GET', 'POST'])
@permission_classes([IsAuthenticated])
def message_list(request):
    if request.method == 'GET':
        messages = Message.objects.all()
        serializer = MessageSerializer(messages, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = MessageSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(sender=request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

Utilisateurs/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Administrateur</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    {% block css %}
    {% endblock %}
</head>
<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
{% block content %}
    <!-- Votre contenu ici -->
{% endblock %}

<!-- Popper.js -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<!-- jQuery (included in Bootstrap bundle) -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- OverlayScrollbars JS -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE JS -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<!-- jQuery Mousewheel -->
<script src="{% static 'plugins/jquery-mousewheel/jquery.mousewheel.js' %}"></script>
<!-- Raphael JS -->
<script src="{% static 'plugins/raphael/raphael.min.js' %}"></script>
<!-- jQuery Mapael -->
<script src="{% static 'plugins/jquery-mapael/jquery.mapael.min.js' %}"></script>
<script src="{% static 'plugins/jquery-mapael/maps/usa_states.min.js' %}"></script>
<!-- Chart.js -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">


<script>
    $(document).ready(function () {
        function handleScroll() {
            var scroll = $(window).scrollTop();
            var navbar = $(".navbar-nav");

            if (scroll > 100) {
                navbar.addClass("scrolling");
            } else {
                navbar.removeClass("scrolling");
            }
        }

        $(window).scroll(handleScroll);
        handleScroll();
    });
</script>
</body>
</html>

Utilisateurs/templates/confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!-- templates/confirmation.html -->
<form method="post">
    {% csrf_token %}
    <label for="confirmation_code">Code de confirmation :</label>
    <input type="text" name="confirmation_code" required>
    <button type="submit">Confirmer</button>
</form>

</body>
</html>

Utilisateurs/templates/connexion.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <link href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css" rel="stylesheet" />
    <title>Login</title>
    <style>
        .error {
            border: 1px solid red;
            background-color: #ffdddd;
        }
        .error-message {
            color: red;
            font-size: 14px;
            margin-top: 5px;
        }
        .login__button{
            text-align: center;
            margin-left: auto;
            margin-right: auto;
            border: none;
            width: 100%;
        }
        .login__forms:hover{
            transform: scale(1.05);
        }
    </style>
</head>
<body>

<div class="login">
    <div class="login__content">
        <div class="login__img">
            <img src="{% static 'assets/img/img-login.svg'%}" alt="Login" />
        </div>

        <div class="login__forms">
            <form method="post" class="login__registre" id="login-in">

                {% csrf_token %}
                <h1 class="login__title">Connexion</h1>

                <div class="login__box">
                    <i class="bx bx-user login__icon"></i>
                    {{ form.username }}
                </div>

                <div class="login__box">
                    <i class="bx bx-lock login__icon"></i>
                    {{ form.password }}
                </div>

                <a href="" class="login__forgot">Mot de passe oublié ?</a>
                <button type="submit" name="submit" class="login__button">Se connecter</button>

                <div>
                    <span class="login__account">Vous n'avez pas de compte ?</span>
                    <span class="login__signin" id="sign-up"><a href="{% url 'utilisateurs:inscription'%}">Créer un compte</a></span>
                </div>
            </form>

        </div>
    </div>
</div>

<script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>

Utilisateurs/templates/index2.html
{% extends 'base.html' %}
{% if user.is_authenticated %}
{% load static %}
{% block content%}
<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    {% include 'nav.html' %}
<div class="wrapper">
  <div class="content-wrapper">
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard v2</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v2</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- Left col -->
          <div class="col-md-8">
            <div class="row">
              <div class="col-md-6">
                <!-- DIRECT CHAT -->
                <div class="card direct-chat direct-chat-warning">
                  <div class="card-header">
                    <h3 class="card-title">Conversation avec (Nom de l'utilisateurs qui recois le message)</h3>

                    <div class="card-tools">
                      <span title="3 New Messages" class="badge badge-warning">3</span>
                      <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                      </button>
                      <button type="button" class="btn btn-tool" title="Contacts" data-widget="chat-pane-toggle">
                        <i class="fas fa-comments"></i>
                      </button>
                      <button type="button" class="btn btn-tool" data-card-widget="remove">
                        <i class="fas fa-times"></i>
                      </button>
                    </div>
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    <!-- Conversations are loaded here -->
                    <div class="direct-chat-messages">
                      <!-- Message. Default to the left -->
                      <div class="direct-chat-msg">
                        <div class="direct-chat-infos clearfix">
                          <span class="direct-chat-name float-left">Nom de l'utilisateurs qui recois le message</span>
                          <span class="direct-chat-timestamp float-right">23 Jan 2:00 pm</span>
                        </div>
                        <!-- /.direct-chat-infos -->
                        <img class="direct-chat-img" src="dist/img/user1-128x128.jpg" alt="message user image">
                        <!-- /.direct-chat-img -->
                        <div class="direct-chat-text">
                            message de l'utilisateurs qui recois le message
                        </div>
                        <!-- /.direct-chat-text -->
                      </div>
                      <!-- /.direct-chat-msg -->

                      <!-- Message to the right -->
                      <div class="direct-chat-msg right">
                        <div class="direct-chat-infos clearfix">
                          <span class="direct-chat-name float-right">Nom de l'utilisateurs qui envoi le message</span>
                          <span class="direct-chat-timestamp float-left">23 Jan 2:05 pm</span>
                        </div>
                        <!-- /.direct-chat-infos -->
                        <img class="direct-chat-img" src="dist/img/user3-128x128.jpg" alt="message user image">
                        <!-- /.direct-chat-img -->
                        <div class="direct-chat-text">
                            messhtrhage de l'utilisateurs qui envoi le message
                        </div>
                        <!-- /.direct-chat-text -->
                      </div>
                    <!-- /.direct-chat-pane -->
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                    <form action="#" method="post">
                      <div class="input-group">
                        <input type="text" name="message" placeholder="Type Message ..." class="form-control">
                        <span class="input-group-append">
                          <button type="button" class="btn btn-warning">Envoyer</button>
                        </span>
                      </div>
                    </form>
                  </div>
                  <!-- /.card-footer-->
                </div>
                <!--/.direct-chat -->
              </div>
              <!-- /.col -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
      </div>
    </section>
  </div>
  <aside class="control-sidebar control-sidebar-dark">
  </aside>
</div>
{% endblock %}
{% else %}
Vous devez être connecté pour accéder à cette page. <a href="{% url 'utilisateurs:Connexion' %}">Se connecter</a>.
{% endif %}

Utilisateurs/templates/inscription.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body class="hold-transition register-page">
<div class="register-box">
    <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <a href="../../index2.html" class="h1"><b>inscription</b></a>
        </div>
        <div class="card-body">

            <form method="post" class="login__registre" id="login-in" action="{% url 'utilisateurs:inscription'%}" enctype="multipart/form-data">
            {% csrf_token %}
                {% if form.nom.errors %}
                    <div class="error-message text-danger">
                        {{ form.nom.errors.0 }}
                    </div>
                {% endif %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Nom" name="nom">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>

                        </div>

                    </div>

                </div>
                {% if form.prenom.errors %}
                    <div class="error-message text-danger">
                        {{ form.prenom.errors.0 }}
                    </div>
                {% endif %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Prenom"  name="prenom">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                {% if form.username.errors %}
                    <div class="error-message text-danger">
                        {{ form.username.errors.0 }}
                    </div>
                {% endif %}
                <div class="input-group mb-3">
                    <input type="number" class="form-control" placeholder="Numero" name="username">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-phone"></span>
                        </div>
                    </div>
                </div>

                <div class="input-group mb-3">
                    <input type="file" class="form-control" placeholder="Choisir une image" name="photo">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-image"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="Mot de passe" name="password1">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="Confirmer le mot de passe" name="password2">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                {% if form.password1.errors %}
                    <div class="error-message text-danger">
                        {{ form.password1.errors.0 }}
                    </div>
                {% endif %}
                {% if form.password2.errors %}
                    <div class="error-message text-danger">
                        {{ form.password2.errors.0 }}
                    </div>
                {% endif %}

                <!-- /.col -->
                    <div class="">
                        <button type="submit" class="btn btn-primary btn-block">S'inscrire</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <div class="social-auth-links text-center">
                <a href="#" class="btn btn-block btn-primary">
                    <i class="fab fa-facebook mr-2"></i>
                    Sign up using Facebook
                </a>
                <a href="#" class="btn btn-block btn-danger">
                    <i class="fab fa-google-plus mr-2"></i>
                    Sign up using Google+
                </a>
            </div>

            <a href="{% url 'utilisateurs:connexion' %}" class="text-center">J'ai déjà un compte</a>
        </div>
        <!-- /.form-box -->
    </div><!-- /.card -->
</div>
{% endblock %}