Admin/urls.py
# admin/urls.py
from django.urls import path
from .views import admin_dashboard, admin_create_user, admin_edit_user, admin_delete_user, tous_les_user, utilisateur, \
    Messages, blog_list, BlogPostDetailView, share_post, All_Blog, delete_post, edit_post, view_blog, \
    active_utilisateur, desactive_utilisateur, Info_du_site, modifier_parametres, create_blog

app_name = 'admin'
urlpatterns = [
    path('dashboard/', admin_dashboard, name='admin_dashboard'),
    path('create/', admin_create_user, name='admin_create_user'),
    path('edit/<int:user_id>/', admin_edit_user, name='admin_edit_user'),
    path('delete/<int:user_id>/', admin_delete_user, name='admin_delete_user'),
    path('user/', tous_les_user, name='tous_les_user'),
    path('utilisateur/', utilisateur, name='utilisateur'),
    path('messages/<int:user_id>/', Messages, name='messages'),
    path('create_blog/', create_blog, name='create'),
    path('list/', blog_list, name='post'),
    path('All_Blog/', All_Blog, name='All_Blog'),
    path('<int:blog_id>/', BlogPostDetailView.as_view(), name='blog_detail'),
    path('<int:blog_id>/share/', share_post, name='share_post'),
    path('delete_post/<int:post_id>/', delete_post, name='delete_post'),
    path('edit_post/<int:post_id>/', edit_post, name='edit_post'),
    path('view_blog/<int:post_id>/', view_blog, name='view_blog'),
    path('Active_utilisateur/<int:utilisateur_id>/', active_utilisateur, name='active_utilisateur'),
    path('Desactive_utilisateur/<int:utilisateur_id>/', desactive_utilisateur, name='desactive_utilisateur'),
    path('info_du_site/', Info_du_site, name='info_du_site'),
    path('modifier_parametres/<int:pk>/', modifier_parametres, name='modifier_parametres'),
]

Projet/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
                  path('', include('Site.urls')),
                  path('Utilisateurs/', include('Utilisateurs.urls')),
                  path('administrer/', include('Admin.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

Site/urls.py
# Site/urls.py
from django.urls import path

from Site import views
from Site.views import Index

app_name = 'site'

urlpatterns = [
    path('', Index, name='index'),
    path('publication/<int:pk>/', views.publication_detail, name='publication_detail'),
]

Utilisateurs/models.py
# Utilisateurs/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models import Q
from django.forms import forms
from django.urls import reverse
from django.utils import timezone
from django.utils.timesince import timesince
from multiupload.fields import MultiFileField


class CustomUserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(username, password, **extra_fields)

    def get_user_messages(self, user, recipient):
        return Message.objects.filter(Q(sender=user, receiver=recipient) | Q(sender=recipient, receiver=user))


class CustomUser(AbstractBaseUser):
    ROLE_CHOICES = [
        ('user', 'User'),
        ('admin', 'Admin'),
    ]

    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='user')
    username = models.CharField(max_length=15, unique=True)
    nom = models.CharField(max_length=30)
    prenom = models.CharField(max_length=30)
    photo = models.ImageField(upload_to='profile_photos/', null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_online = models.BooleanField(default=False)
    last_logout = models.DateTimeField(default=timezone.now)
    unread_messages_count = models.IntegerField(default=0)

    @property
    def get_unread_messages(self):
        return Message.objects.filter(receiver=self, is_read=False).count()

    def time_since_last_logout(self):
        if self.last_logout:
            time_since_logout = timesince(self.last_logout)
            return f"En ligne il y a {time_since_logout}"
        else:
            return "Hors ligne (date de déconnexion non disponible)"

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['nom', 'prenom']

    def __str__(self):
        return f"{self.prenom} {self.nom}"


class Message(models.Model):
    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def mark_as_read(self):
        self.is_read = True
        self.save()

    def __str__(self):
        return f'{self.sender} to {self.receiver} ({self.timestamp})'


class BlogPost(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(get_user_model(), related_name='blog_likes', blank=True)
    shares = models.IntegerField(default=0)
    image = models.ImageField(upload_to='blog_images/', verbose_name="Image d'accueil", blank=True)
    views = models.IntegerField(default=0)

    def get_delete_url(self):
        return reverse('delete_post', args=[str(self.id)])

    def increment_views(self):
        self.views += 1
        self.save()

    def get_like_count(self):
        return self.likes.count()

    def __str__(self):
        return f"Image {self.pk}"

    def time_pub_date_since(self):
        if self.pub_date:
            time_since_pub_date = timesince(self.pub_date)
            return f"Publier il y a {time_since_pub_date}"
        else:
            return "Hors ligne (date de déconnexion non disponible)"

    def get_absolute_url(self):
        return reverse('blog:blog_detail', args=[str(self.id)])

    def __str__(self):
        return self.title

Utilisateurs/forms.py
# Utilisateurs/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import ClearableFileInput

from .models import CustomUser, BlogPost
from django import forms


class UserRegistrationForm(UserCreationForm):
    photo = forms.ImageField(required=False)
    username = forms.CharField(max_length=15, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Numéro de téléphone'}))
    role = forms.ChoiceField(choices=CustomUser.ROLE_CHOICES, required=False, widget=forms.Select(
        attrs={'class': 'form-control'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'nom', 'prenom', 'photo', 'password1', 'password2', 'role']

        def clean(self):
            cleaned_data = super().clean()

            password1 = cleaned_data.get("password1")
            password2 = cleaned_data.get("password2")

            if password1 and password2 and password1 != password2:
                self.add_error('password2', "Les deux mots de passe ne correspondent pas.")

            return cleaned_data

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['nom'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Nom'})
        self.fields['prenom'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Prénom'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Mot de passe'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Confirmez le mot de passe'})
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Numéro de téléphone'})


class UserAuthenticationForm(AuthenticationForm):
    username = forms.CharField(max_length=15, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Numéro de téléphone'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'password']


class MessageForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea)


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'content', 'image']


class ActivateUserForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput())


class DeactivateUserForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput())

Admin/templates/publication/create_blog.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Création de Blog</title>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/lang/summernote-fr-FR.min.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }

        .wrapper {
            max-width: 800px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #007bff;
        }

        label {
            display: block;
            margin-top: 10px;
            font-weight: bold;
        }

        input,
        textarea {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        .custom-file {
            position: relative;
            display: inline-block;
            width: 100%;
            height: 40px;
            margin-top: 5px;
        }

        .custom-file-input {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            opacity: 0;
        }

        .custom-file-label {
            display: block;
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
            background-color: #007bff;
            color: #fff;
            border-radius: 4px;
            padding: 10px;
            cursor: pointer;
        }

        .custom-file-label::after {
            content: "Choisir une image";
        }

        button {
            background-color: #28a745;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
</head>
<body>
<div class="wrapper">
    <h1>Ajout d'un blog</h1>
    <form method="post" action="{% url 'admin:create' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_title">Titre</label>
        <input type="text" id="id_title" name="title">

        <label for="summernote">Contenu</label>
        <textarea id="summernote" name="content" rows="4"></textarea>

        <label for="id_image">Image</label>
        <div class="custom-file">
            <input type="file" name="image" class="custom-file-input" id="id_image">
            <label class="custom-file-label" for="id_image">Choisir une image</label>
        </div>

        <button style="width: 100%" type="submit">Publier</button>
    </form>

    <script>
        $('#summernote').summernote({
            placeholder: 'Rediger votre contenu ici',
            minHeight: 400,
            lang: 'fr-FR',  // Utilise le fichier de traduction français
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'video']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ]
        });
    </script>
</div>
</body>
</html>

Admin/templates/publication/edit_post.html
{% extends 'base.html' %}
{% if user.is_authenticated %}
    {% load static %}
    {% block content%}
        <body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
        <style>
            .success-message {
                background-color: #d4edda;
                color: #155724;
                padding: 10px;
                margin-bottom: 10px;
                border: 1px solid #c3e6cb;
                border-radius: 5px;
            }
        </style>
        {% include 'nav.html' %}
        <div class="wrapper">
        <div class="wrapper">
        <div class="content-wrapper">
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>Modifier d'un blog</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Accueil</a></li>
                                <li class="breadcrumb-item active">Modifier une publication</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </section>
            <section class="content">
                <form method="post" action="{% url 'admin:edit_post' post_id=post.id %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Modification</h3>

                                    <div class="card-tools">
                                        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                            <i class="fas fa-minus"></i>
                                        </button>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="id_title">Titre</label>
                                        <input type="text" id="id_title" name="title" class="form-control" value="{{ post.title }}">
                                    </div>
                                    <div class="form-group">
                                        <label for="id_content">Contenu</label>
                                        <textarea id="id_content" name="content" class="form-control" rows="4">{{ post.content }}</textarea>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_image">Image</label>
                                        <div class="input-group">
                                            <div class="custom-file">
                                                <input type="file" name="image" class="custom-file-input" id="id_image">
                                                <label class="custom-file-label" for="id_image">Choisir une image</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <button type="submit" class="btn btn-warning">Modifier</button>
                        </div>
                    </div>
                </form>


            </section>
        </div>
    {% endblock %}
{% else %}
    Vous devez être connecté pour accéder à cette page. <a href="">Se connecter</a>.
{% endif %}

Admin/templates/publication/post.html
<!-- Admin/templates/dashboard.html -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    {% include 'nav.html' %}
    <div class="wrapper">
    <div class="wrapper">
    <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Widgets</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Widgets</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    {% for blog_posts in blog_posts %}
        <div class="row restorable-post">
            <div class="col-lg-3 d-none d-lg-block"></div>
            <div class="col-md-12 col-lg-6">
                <!-- Box Comment -->
                <div class="card card-widget">
                    <div class="card-header">
                        <div class="user-block">
                            <img class="img-circle" src="{{ blog_posts.author.photo.url }}" alt="User Image">
                            <span class="username"><a href="#">{{ blog_posts.author.nom }}</a></span>
                            <span class="description text-white">{{ blog_posts.time_pub_date_since }}</span>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <!-- post.html -->
                        <img class="img-fluid pad" src="{% if blog_posts.has_image %}{{ blog_posts.image.url }}{% else %}URL_PAR_DEFAUT_SI_PAS_D_IMAGE{% endif %}" alt="Photo">


                        <div id="content{{ blog_posts.id }}" data-content="{{ blog_posts.content }}">
                            <p>{{ blog_posts.content|truncatewords:10 }}</p>
                        </div>
                        {% if blog_posts.content|length > 10 %}
                            <button type="button" class="btn btn-link" onclick="toggleContent({{ blog_posts.id }})">
                                {% if blog_posts.show_full_content %}Voir moins{% else %}Voir plus{% endif %}
                            </button>
                        {% endif %}


                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i> Share</button>
                        <form method="post" action="{% url 'admin:post' %}">
                            {% csrf_token %}
                            <input type="hidden" name="blog_id" value="{{ blog_posts.id }}">
                            <button type="submit" class="btn btn-default btn-sm">
                                <i class="far fa-thumbs-up"></i> Like
                            </button>
                        </form>
                        <span id="likeCount{{ blog_posts.id }}" class="float-right text-muted">{{ blog_posts.get_like_count }} likes - 3 comments</span>

                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer card-comments">
                        <div class="card-comment">
                            <!-- User image -->
                            <img class="img-circle img-sm" src="" alt="User Image">

                            <div class="comment-text">
                    <span class="username">
                      Maria Gonzales
                      <span class="text-muted float-right">8:03 PM Today</span>
                    </span><!-- /.username -->
                                It is a long established fact that a reader will be distracted
                                by the readable content of a page when looking at its layout.
                            </div>
                            <!-- /.comment-text -->
                        </div>
                    </div>
                    <!-- /.card-footer -->
                    <div class="card-footer">
                        <form action="#" method="post">
                            <img class="img-fluid img-circle img-sm" src="../dist/img/user4-128x128.jpg" alt="Alt Text">
                            <!-- .img-push is used to add margin to elements next to floating images -->
                            <div class="img-push">
                                <input type="text" class="form-control form-control-sm" placeholder="Press enter to post comment">
                            </div>
                        </form>
                    </div>
                    <!-- /.card-footer -->
                </div>
                <!-- /.card -->
            </div>

            <div class="col-lg-3 d-none d-lg-block"></div>
            <!-- /.col -->
        </div>
    {% endfor %}
    <script>
        function toggleContent(blogId) {
            var contentDiv = document.getElementById("content" + blogId);
            var fullContent = contentDiv.getAttribute("data-content");
            var isFullContentDisplayed = contentDiv.classList.contains("full-content");

            if (isFullContentDisplayed) {
                contentDiv.innerHTML = "<p>" + fullContent.substring(0, 100) + "...</p>";
                contentDiv.classList.remove("full-content");
            } else {
                contentDiv.innerHTML = "<p>" + fullContent + "</p>";
                contentDiv.classList.add("full-content");
            }

            // Mettez à jour le texte du bouton
            var button = document.querySelector("#content" + blogId + " button");
            button.textContent = isFullContentDisplayed ? "Voir moins" : "Voir moins";
        }
    </script>

{% endblock %}

Admin/templates/publication/tout_les_blog.html
<!-- Admin/templates/dashboard.html -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
{% include 'nav.html' %}
<div class="wrapper">
    <div class="wrapper">
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>Tous les postes</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Accueil</a></li>
                                <li class="breadcrumb-item active">Tout les postes</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>
            <section class="content">

                <!-- Default box -->
                {% for tout_les_blog in tout_les_blog %}
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"> {{ tout_les_blog.time_pub_date_since }}</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <table class="table table-striped projects">
                            <thead>
                            <tr>
                                <th style="width: 1%">
                                    Titre
                                </th>
                                <th style="width: 20%">
                                    Contenu
                                </th>
                                <th style="width: 30%">
                                    Image
                                </th>
                                <th>
                                    Project Progress
                                </th>
                                <th style="width: 8%" class="text-center">
                                    Status
                                </th>
                                <th style="width: 20%">
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>
                                    {{ tout_les_blog.title }}
                                </td>
                                <td>
                                    <a>
                                        {{ tout_les_blog.content|truncatewords:20|safe }}
                                    </a>
                                    <br/>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <img class="img-fluid pad" src="{{ tout_les_blog.image.url }}" alt="Photo" style="max-width: 200px">
                                    </ul>
                                </td>
                                <td class="project_progress">
                                    <div class="progress progress-sm">
                                        <div class="progress-bar bg-green" role="progressbar" aria-valuenow="57" aria-valuemin="0" aria-valuemax="100" style="width: 57%">
                                        </div>
                                    </div>
                                    <small>
                                        57% Complete
                                    </small>
                                </td>
                                <td class="project-state">
                                    <span class="badge badge-success">Success</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="{% url 'admin:view_blog' post_id=tout_les_blog.id %}">
                                        <i class="fas fa-folder"></i> Voir le blog
                                    </a>


                                    <a class="btn btn-info btn-sm" href="{% url 'admin:edit_post' post_id=tout_les_blog.id %}">
                                        <i class="fas fa-pencil-alt"></i>
                                        Modifier
                                    </a>

                                    <a class="btn btn-danger btn-sm" href="{% url 'admin:delete_post' post_id=tout_les_blog.id %}">
                                        <i class="fas fa-trash"></i>
                                        Supprimer
                                    </a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                {% endfor %}
            </section>

{% endblock %}