Admin/urls.py
# admin/urls.py
from django.urls import path
from .views import admin_dashboard, admin_create_user, admin_edit_user, admin_delete_user, tous_les_user, utilisateur, \
    Messages, blog_list, BlogPostDetailView, share_post, All_Blog, delete_post, edit_post, view_blog, \
    active_utilisateur, desactive_utilisateur, Info_du_site, modifier_parametres, create_blog

app_name = 'admin'
urlpatterns = [
    path('dashboard/', admin_dashboard, name='admin_dashboard'),
    path('create/', admin_create_user, name='admin_create_user'),
    path('edit/<int:user_id>/', admin_edit_user, name='admin_edit_user'),
    path('delete/<int:user_id>/', admin_delete_user, name='admin_delete_user'),
    path('user/', tous_les_user, name='tous_les_user'),
    path('utilisateur/', utilisateur, name='utilisateur'),
    path('messages/<int:user_id>/', Messages, name='messages'),
    path('create_blog/', create_blog, name='create'),
    path('list/', blog_list, name='post'),
    path('All_Blog/', All_Blog, name='All_Blog'),
    path('<int:blog_id>/', BlogPostDetailView.as_view(), name='blog_detail'),
    path('<int:blog_id>/share/', share_post, name='share_post'),
    path('delete_post/<int:post_id>/', delete_post, name='delete_post'),
    path('edit_post/<int:post_id>/', edit_post, name='edit_post'),
    path('view_blog/<int:post_id>/', view_blog, name='view_blog'),
    path('Active_utilisateur/<int:utilisateur_id>/', active_utilisateur, name='active_utilisateur'),
    path('Desactive_utilisateur/<int:utilisateur_id>/', desactive_utilisateur, name='desactive_utilisateur'),
    path('info_du_site/', Info_du_site, name='info_du_site'),
    path('modifier_parametres/<int:pk>/', modifier_parametres, name='modifier_parametres'),
]

Projet/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
                  path('', include('Site.urls')),
                  path('Utilisateurs/', include('Utilisateurs.urls')),
                  path('administrer/', include('Admin.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

Site/urls.py
# Site/urls.py
from django.urls import path

from Site import views
from Site.views import Index

app_name = 'site'

urlpatterns = [
    path('', Index, name='index'),
    path('publication/<int:pk>/', views.publication_detail, name='publication_detail'),
]

Utilisateurs/models.py
# Utilisateurs/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models import Q
from django.forms import forms
from django.urls import reverse
from django.utils import timezone
from django.utils.timesince import timesince
from multiupload.fields import MultiFileField


class CustomUserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(username, password, **extra_fields)

    def get_user_messages(self, user, recipient):
        return Message.objects.filter(Q(sender=user, receiver=recipient) | Q(sender=recipient, receiver=user))


class CustomUser(AbstractBaseUser):
    ROLE_CHOICES = [
        ('user', 'User'),
        ('admin', 'Admin'),
    ]

    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='user')
    username = models.CharField(max_length=15, unique=True)
    nom = models.CharField(max_length=30)
    prenom = models.CharField(max_length=30)
    photo = models.ImageField(upload_to='profile_photos/', null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_online = models.BooleanField(default=False)
    last_logout = models.DateTimeField(default=timezone.now)
    unread_messages_count = models.IntegerField(default=0)

    @property
    def get_unread_messages(self):
        return Message.objects.filter(receiver=self, is_read=False).count()

    def time_since_last_logout(self):
        if self.last_logout:
            time_since_logout = timesince(self.last_logout)
            return f"En ligne il y a {time_since_logout}"
        else:
            return "Hors ligne (date de déconnexion non disponible)"

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['nom', 'prenom']

    def __str__(self):
        return f"{self.prenom} {self.nom}"


class Message(models.Model):
    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def mark_as_read(self):
        self.is_read = True
        self.save()

    def __str__(self):
        return f'{self.sender} to {self.receiver} ({self.timestamp})'


class BlogPost(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(get_user_model(), related_name='blog_likes', blank=True)
    shares = models.IntegerField(default=0)
    image = models.ImageField(upload_to='blog_images/', verbose_name="Image d'accueil", blank=True)
    views = models.IntegerField(default=0)

    def get_delete_url(self):
        return reverse('delete_post', args=[str(self.id)])

    def increment_views(self):
        self.views += 1
        self.save()

    def get_like_count(self):
        return self.likes.count()

    def __str__(self):
        return f"Image {self.pk}"

    def time_pub_date_since(self):
        if self.pub_date:
            time_since_pub_date = timesince(self.pub_date)
            return f"Publier il y a {time_since_pub_date}"
        else:
            return "Hors ligne (date de déconnexion non disponible)"

    def get_absolute_url(self):
        return reverse('blog:blog_detail', args=[str(self.id)])

    def __str__(self):
        return self.title

Utilisateurs/forms.py
# Utilisateurs/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import ClearableFileInput

from .models import CustomUser, BlogPost
from django import forms


class UserRegistrationForm(UserCreationForm):
    photo = forms.ImageField(required=False)
    username = forms.CharField(max_length=15, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Numéro de téléphone'}))
    role = forms.ChoiceField(choices=CustomUser.ROLE_CHOICES, required=False, widget=forms.Select(
        attrs={'class': 'form-control'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'nom', 'prenom', 'photo', 'password1', 'password2', 'role']

        def clean(self):
            cleaned_data = super().clean()

            password1 = cleaned_data.get("password1")
            password2 = cleaned_data.get("password2")

            if password1 and password2 and password1 != password2:
                self.add_error('password2', "Les deux mots de passe ne correspondent pas.")

            return cleaned_data

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['nom'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Nom'})
        self.fields['prenom'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Prénom'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Mot de passe'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Confirmez le mot de passe'})
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Numéro de téléphone'})


class UserAuthenticationForm(AuthenticationForm):
    username = forms.CharField(max_length=15, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Numéro de téléphone'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'password']


class MessageForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea)


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'content', 'image']


class ActivateUserForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput())


class DeactivateUserForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput())

Admin/templates/add_utilisateur.html
<!-- Admin/templates/user_list.html -->
{% extends 'base.html' %}
{% if user.is_authenticated %}
    {% load static %}
    {% block content%}
        <body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
        <style>
            .success-message {
                background-color: #d4edda;
                color: #155724;
                padding: 10px;
                margin-bottom: 10px;
                border: 1px solid #c3e6cb;
                border-radius: 5px;
            }
        </style>
        {% include 'nav.html' %}
        <div class="wrapper">
        <div class="wrapper">
        <div class="content-wrapper">
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>Enregistrement d'un utilisateur</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">Enregistrement d'un utilisateur</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </section>
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Les informations de l'utilisateur</h3>
                                </div>
                                <form method="post" action="{% url 'admin:admin_create_user' %}" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label for="id_nom">Nom</label>
                                            <input type="text" name="nom" class="form-control" id="id_nom" placeholder="Nom" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="id_prenom">Prénom</label>
                                            <input type="text" name="prenom" class="form-control" id="id_prenom" placeholder="Prénom" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="id_username">Numéro de téléphone</label>
                                            <input type="number" name="username" class="form-control" id="id_username" placeholder="Numéro de téléphone" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="id_password1">Mot de passe</label>
                                            <input type="password" name="password1" class="form-control" id="id_password1" placeholder="Mot de passe" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="id_password2">Confirmez le mot de passe</label>
                                            <input type="password" name="password2" class="form-control" id="id_password2" placeholder="Confirmez le mot de passe" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="id_role">Role</label>
                                            <select name="role" class="form-control" id="id_role">
                                                {% for value, label in form.role.field.choices %}
                                                    <option value="{{ value }}">{{ label }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="id_photo">Image</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file" name="photo" class="custom-file-input" id="id_photo">
                                                    <label class="custom-file-label" for="id_photo">Choisir une image</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                                        <div id="success-message" class="success-message" >
                                            {% for message in messages %}
                                                {{ message }}
                                            {% endfor %}
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <script>
            // JavaScript to hide the success message after 3 seconds
            document.addEventListener('DOMContentLoaded', function() {
                setTimeout(function() {
                    document.getElementById('success-message').style.display = 'none';
                }, 3000);
            });
        </script>
    {% endblock %}
{% else %}
    Vous devez être connecté pour accéder à cette page. <a href="">Se connecter</a>.
{% endif %}

Admin/templates/delete_user.html
<!-- Admin/templates/user_list.html -->
{% extends 'base.html' %}
{% if user.is_authenticated %}
    {% load static %}
    {% block content%}
        <body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
        {% include 'nav.html' %}
        <div class="wrapper">
        <div class="wrapper">
        <div class="content-wrapper">
            <div class="container mt-5">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">Confirmation de suppression</h2>
                        <p class="card-text">Êtes-vous sûr de vouloir supprimer l'utilisateur {{ utilisateur.username }} ?</p>
                        <form method="post" action="{% url 'admin:admin_delete_user' utilisateur.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Supprimer</button>
                            <a href="{% url 'admin:tous_les_user' %}" class="btn btn-secondary">Annuler</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
{% else %}
    Vous devez être connecté pour accéder à cette page. <a href="">Se connecter</a>.
{% endif %}

Admin/templates/user_list.html
<!-- Admin/templates/user_list.html -->
{% extends 'base.html' %}
{% if user.is_authenticated %}
    {% load static %}
    {% block content%}
        <body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
        <style>
            .success-message {
                background-color: #d4edda;
                color: #155724;
                padding: 10px;
                margin-bottom: 10px;
                border: 1px solid #c3e6cb;
                border-radius: 5px;
            }
            .card.online {
                border: 2px solid #28a745;
            }

            .card.offline {
                border: 2px solid #dc3545;
            }

            .status-online {
                color: #28a745;
            }

            .status-offline {
                color: #dc3545;
            }

        </style>
        {% include 'nav.html' %}
        <div class="wrapper">
            <div class="wrapper">
                <div class="content-wrapper">
                    <section class="content-header">
                        <div class="container-fluid">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h1>Tout les utilisateurs</h1>
                                    {% if messages %}
                                    <div id="success-message" class="success-message" >

                                            {{ messages }}


                                    </div>
                                    {% endif %}
                                </div>
                                <div class="col-sm-6">
                                    <ol class="breadcrumb float-sm-right">
                                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                                        <li class="breadcrumb-item active"> Profile des utilisateurs</li>
                                    </ol>
                                </div>
                            </div>
                        </div><!-- /.container-fluid -->
                    </section>

                    <!-- Main content -->
                    <section class="content">
                        <div class="container-fluid">
                            {% if all_users %}
                            <div class="row">
                                {% for utilisateur in all_users %}
                                    <div class="col-md-4 col-12">
                                        <div class="card card-primary card-outline">
                                            <div class="card-body box-profile">
                                                <div class="text-center">
                                                    {% if utilisateur.photo %}
                                                        <img class="profile-user-img img-fluid img-circle"
                                                             src="{{ utilisateur.photo.url }}"
                                                             alt="User profile picture">
                                                        {% if utilisateur.is_active == True %}
                                                            <span class="text-success">Compte Actif</span>
                                                        {% else %}
                                                            <i class="fas fa-ban text-danger" disabled></i> Compte désactivé
                                                        {% endif %}
                                                    {% else %}
                                                        <img class="profile-user-img img-fluid img-circle" src="{% static 'images/user4-128x128.jpg' %}" alt="Default profile picture">
                                                        {% if utilisateur.is_active == True %}
                                                            <span class="text-success">Compte Actif</span>
                                                        {% else %}
                                                            <i class="fas fa-ban text-danger" disabled></i> Compte désactivé
                                                        {% endif %}

                                                    {% endif %}
                                                </div>

                                                <h3 class="profile-username text-center">{{ utilisateur.nom }} {{ utilisateur.prenom }}</h3>

                                                <p class="text-muted text-center">{{ utilisateur.username }}</p>
                                                {% if utilisateur.is_online %}
                                                    <span class="status-online">En ligne<span style="font-size: 50px; color:#588113">.</span></span>
                                                {% else %}
                                                    {% if utilisateur.is_active == True %}
                                                    <span class="status-offline">{{ utilisateur.time_since_last_logout }}</span>
                                                    {% else %}
                                                    {% endif %}
                                                {% endif %}

                                                {% if utilisateur.is_active == False %}
                                                    <form method="post" action="{% url 'admin:active_utilisateur' utilisateur.id %}">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-success" {% if utilisateur.is_active == True %}disabled{% endif %}>
                                                            <i class="fas fa-check-circle"></i> Activer
                                                        </button>
                                                    </form>
                                                {% else %}
                                                    <form method="post" action="{% url 'admin:desactive_utilisateur' utilisateur.id %}">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-danger" {% if utilisateur.is_active == False %}disabled{% endif %}>
                                                            <i class="fas fa-times-circle"></i> Désactiver
                                                        </button>
                                                    </form>
                                                {% endif %}




                                                <ul class="list-group list-group-unbordered mb-3">
                                                    <li class="list-group-item">
                                                        <b>Followers</b> <a class="float-right">1,322</a>
                                                    </li>
                                                    <li class="list-group-item">
                                                        <b>Following</b> <a class="float-right">543</a>
                                                    </li>
                                                    <li class="list-group-item">
                                                        <b>Friends</b> <a class="float-right">13,287</a>
                                                    </li>
                                                </ul>

                                                <a href="" class="btn btn-primary btn-block"><b>Mettre les informations a jour</b></a>
                                                <a href="{% url 'admin:admin_delete_user' utilisateur.id %}" class="btn btn-danger btn-block"><b>Supprimer</b></a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            {% else %}
                                <p>Aucun utilisateur n'est disponible.</p>
                            {% endif %}
                        </div>
                    </section>
                </div>
            </div>

        </div>
        <script>
            // JavaScript to hide the success message after 3 seconds
            document.addEventListener('DOMContentLoaded', function() {
                setTimeout(function() {
                    document.getElementById('success-message').style.display = 'none';
                }, 3000);
            });
        </script>

    {% endblock %}
{% else %}
Vous devez être connecté pour accéder à cette page. <a href="">Se connecter</a>.
{% endif %}

Admin/templates/utlisateurs.html
<!-- Admin/templates/user_list.html -->
{% extends 'base.html' %}
{% if user.is_authenticated %}
    {% load static %}
    {% block content%}
        <body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
        {% include 'nav.html' %}
        <div class="wrapper">
            <div class="wrapper">
                <div class="content-wrapper">
                    <section class="content-header">
                        <div class="container-fluid">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h1>Tout les utilisateurs</h1>
                                    <div id="success-message" class="success-message" >
                                        {% for message in messages %}
                                            {{ message }}
                                        {% endfor %}

                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <ol class="breadcrumb float-sm-right">
                                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                                        <li class="breadcrumb-item active"> Profile des utilisateurs</li>
                                    </ol>
                                </div>
                            </div>
                        </div><!-- /.container-fluid -->
                    </section>

                    <!-- Main content -->
                    <section class="content">
                        <div class="container-fluid">
                            {% if all_users %}
                                <div class="row">
                                    {% for utilisateur in all_users %}
                                        <div class="col-md-4 col-12">
                                            <div class="card card-primary card-outline">
                                                <div class="card-body box-profile">
                                                    <div class="text-center">
                                                        {% if utilisateur.photo %}
                                                            <img class="profile-user-img img-fluid img-circle"
                                                                 src="{{ utilisateur.photo.url }}"
                                                                 alt="User profile picture">
                                                        {% else %}
                                                            <img class="profile-user-img img-fluid img-circle"
                                                                 src="{% static 'images/user4-128x128.jpg' %}"
                                                                 alt="Default profile picture">
                                                        {% endif %}
                                                    </div>

                                                    <h3 class="profile-username text-center">{{ utilisateur.nom }} {{ utilisateur.prenom }}</h3>

                                                    <p class="text-muted text-center">{{ utilisateur.username }}</p>
                                                    {% if utilisateur.is_online %}
                                                        <span class="status-online">En ligne<span style="font-size: 60px; color:#588113">.</span></span>
                                                    {% else %}
                                                        <span class="status-offline">{{ utilisateur.time_since_last_logout }}</span>
                                                    {% endif %}



                                                    <ul class="list-group list-group-unbordered mb-3">
                                                        <li class="list-group-item">
                                                            <b>Followers</b> <a class="float-right">1,322</a>
                                                        </li>
                                                        <li class="list-group-item">
                                                            <b>Following</b> <a class="float-right">543</a>
                                                        </li>
                                                        <li class="list-group-item">
                                                            <b>Friends</b> <a class="float-right">13,287</a>
                                                        </li>
                                                    </ul>
                                                    <a href="{% url 'admin:messages' utilisateur.id %}" class="btn btn-primary btn-block">
                                                        <b>Messages</b> {% if utilisateur.unread_messages.exists %}(<span style="color: red; font-size:25px">{{ utilisateur.unread_messages.count }}</span>){% endif %}
                                                    </a>

                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            {% else %}
                                <p>Aucun utilisateur n'est disponible.</p>
                            {% endif %}
                        </div>
                    </section>
                </div>
            </div>

        </div>

    {% endblock %}
{% else %}
Vous devez être connecté pour accéder à cette page. <a href="">Se connecter</a>.
{% endif %}